### ISSUE TITLE
Option to expand to leaf descendants in }bedrock.hier.sub.create.byelement

### ISSUE THREAD

**Issue by rk111000** [cubewise-code/bedrock#272] opened 2021-07-20 06:17 UTC
Describe the bug
Try to Create Subset by specified consolidation elements.

【For example】
Dimension : Version
Element  : 
　All Version 
　　100 
　　200 
　　000 
　All Version difference 
　　000 vs 100   (has two elements "000","100")
　　000 vs 200  (has two elements "000","200")

Execute Process Parameters：
        nRet = ExecuteProcess('}bedrock.hier.sub.create.byelement',
            'pDim', 'Version',
            'pHier', '',
            'pSub', 'TestSubset',
            'pEle' , '000 vs 108 & 000 vs 200',
            'pDelim', '',
            'pAddToSubset', 0,
            'pAlias', '' ,
            'pTemp', 0 
        );

Expected result ：
　000 vs 100 
　000 vs 200 

Actual result：
　_100
　000_
　000 vs 100
　_200
　000_
　000 vs 200

I Expect the Subset has only two elements "000 vs 100" and "000 vs 200" , 
but actual subset has leaf elements.

Please fix the }bedrock.hier.sub.create.byelement.

Thanks.

**Comment by lotsaram** [comment] 2021-07-20 07:22
Hi @rk111000 

The primary intention of bedrock is to manipulate TM1 objects via _TurboIntegrator_. Primarily data processing. As numeric data is exclusively stored at leaf intersections the default behaviour when creating subsets from an element filter is always to _expand a consolidated element to include all leaf descendants_, this is the intended behaviour. From the perspective of data processing via views which is what subsets in bedrock are primarily used for it is of no consequence if subsets contain C and N elements as whether to process leaves exclusively or also consolidations is controlled by the ViewExtractSkip properties of the view.

What you observe is therefore expected behaviour as the insumed intent of subsets created by bedrock is for use in constructing views for data processing and not to be consumed by users via and GUI. For view processing the leaf elements are required (except in unusual use cases). **However**, there is also a valid use case for iterating a subset in the abscence of any view, in which case the developer would want absolute control of which elements are added to the subset.

The way to address this would be via a new *pExpand* parameter added to both hier.sub.create.byelement AND hier.sub.create. The default behaviour to support backwards compatibility would be TRUE for this parameter value. This is therefore an enhancement request.

**Comment by lotsaram** [comment] 2022-05-19 13:02
Fixed in #261

**Closed by lotsaram** 2022-05-19 13:02 UTC
Labels: enhancement, question
