### ISSUE TITLE
Bedrock Is Not Copying Calculated Strings

### ISSUE THREAD

**Issue by raeldor** [cubewise-code/bedrock#215] opened 2020-10-22 00:26 UTC
I have a TM1 Bedrock process that is supposed to copy a calculated string to a string field with no calculations.  I am specifying pSuppressConsol as 0 and pSuppressRules as 0, but nothing gets copied.  When I look at the source view created and preview it in 'Create TI Process' as a cube view source, it only has a single record.  When I edit the view, all the fields except one are at the top as filters and there is only one row field.  When I pull all the fields along the top in as rows (to start with there is only one row field, I see more multiple rows.

Why are the fields all along the top as filters?  How am I supposed to get the consolidated data exported this way?  Also, even after pulling the fields down as rows, some of the elements are not expanded, so I'm not seeing ALL the consolidated data.

Surely this can't be correct?

I believe that having put a consolidate element in the filter, that the leaves are not being expanded.  I was trying a cube export and still couldn't get the the levels of the consolidated filter element to expand unless I set pSuppressConsol as 1 (which seems a little odd since I actually WANT consolidated levels).  To get the calculated string to export I also had to set pSuppressZeros as 0, which I also thought was very odd.  There's not pSuppressZeros on the cube copy, so I'm not even sure how I'd get the calculated string to export.

**Comment by lotsaram** [comment] 2020-10-22 08:29
It sounds like you are having some issues supplying the correct filter. If pSupressConsol=1 then any consolidations supplied in the filter will be "expanded" to all leaf descendants, if pSupressConsol=0 then consolidations in the filter are taken as is. I suggest you read this article for more explaination how the filters work https://cubewise.com/blog/bedrock-filter-strings/ 

If you are sure that the filter is correct (e.g. make the view non-temporary and open it in architect using the "export as text data" dialog and manually export to check that the values you want to export are in fact included. _*don't*_ open in the cube viewer!) Then the issue could be caused by the addition of the ViewExtractSkipConsolidatedStringsSet function which is controlled by the parameter pSuppressConsolStrings in the cube.view.create process. For backwards compatibility cube.data.copy calls view.create with a default setting to skip consolidated strings. If this is actually the cause then the solution would be to add a pSuppressConsolStrings parameter to data.copy and pass the parameter value through when creatign the view.

**Comment by raeldor** [comment] 2020-10-22 12:47
Thank you for the prompt reply.  I was reading that article, but having to set pSuppressConsol=1 to get consolidated items OUT seems a little counter-intuitive don't you think?  I did get data out of the cube.data.export using that option, but I think I still had to set pSuppressZeros to get anything out of a calculated field.  Also, is that pSuppressConsol option ONLY bringing leafs? What about the items between the selected consolidated item and the leaf members?  Because this is a string with values at all consolidated levels, those should be exported/copied too.

**Comment by lotsaram** [comment] 2020-10-22 13:24
If you want to export data against consolidations then you need to EITHER not filter on that dimension at all OR you need to explicitly list all members for which you want to export data in the filter.

Also it is typical to not feed string rules (since the purpose of feeders is to drive consolidation whihc doesn't apply to string data). However unless the string rules are fed they will not be exported by a TI process which has ViewExtractSkipZeroesSet flagged true (bedrock pSuppressZero=1). You probably don't want to feed your stiring rules as this could lead to big memory and performance issues, but the only way to then export the data you want is then to use pSuppressZero=0 but be very, very explicit in the filter for the cellset to be exported (as otherwise it's very easy to construct a view which will process until the end of time due to the amount of potential cells it addresses).

You might actually have a case where using an MDX view with NON EMPTY on your string measure might be the most efficient way to go.

**Comment by raeldor** [comment] 2020-10-27 00:31
We are being explicit in the filter to limit the records for the consolidated export, but we can only do it using the export/import calls, because we need to specify the pSuppressZeros=0.  It seems to me that cube copy should also be able to copy consolidated string metrics.  We also have cases where we hold comments on data points using strings. If we need to copy these between forecast iterations then we'd ideally like to be able to do that using the Bedrock cube copy too.  Thank you for your consideration and prompt replys.

**Comment by tomasfelcman** [comment] 2020-11-23 22:23
Hi raeldor,
 I have created pull request with pSupressZero parameter for }bedrock.cube.data.copy process. Calling this process with proper pFilter (having all the necessary consolidated members listed) should work for you in a way tha the consolidated strings do not have to be fed in order for process to work.

**Comment by raeldor** [comment] 2020-11-25 12:10
Hi, Thank you so much for adding this parameter.  I think this will help us greatly to copy strings between cubes for small subsets of the data. Kind regardsRay  Sent from Mail for Windows 10 From: tomasfelcmanSent: Tuesday, November 24, 2020 7:23 AMTo: cubewise-code/bedrockCc: Ray Price; AuthorSubject: Re: [cubewise-code/bedrock] Bedrock Is Not Copying Calculated Strings (#215) Hi raeldor,I have created pull request with pSupressZero parameter for }bedrock.cube.data.copy process. Calling this process with proper pFilter (having all the necessary consolidated members listed) should work for you in a way tha the consolidated strings do not have to be fed in order for process to work.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lotsaram** [comment] 2020-12-09 15:44
Hi @raeldor 
If your string values are **NOT FED** then the enhancement done by @tomasfelcman in #219 will fix your issue _for leaf cells._ However, if you have consolidations with calculated strings these would still be skipped as the cube.data.copy process currently isn't passing a parameter value to the cube.view.create for pSuppressConsolStrings. I will close this issue and create a new ER for that.

**Closed by lotsaram** 2020-12-09 15:44 UTC
Labels: question

**Comment by raeldor** [comment] 2020-12-09 16:58
@lotsaram Thank you for clarifying and following up on this.  Yes, we would definitely need the consolidated strings also copied for the filtered set of the data.

**Comment by ykud** [comment] 2024-04-17 07:30
hi @lotsaram , 
apologies for kicking the dust of this one, but I was just looking at the changes I did to the bedrock process to address a similar requirement and thought it might be an option in general?

I'm adding a `pIncludeDescendants` parameter to the view create process that makes it include all descendants for a consolidated element even if pSuppressConsols = 0 is selected. This allows 'expanding' consolidations without listing all descendent elements in the filter string.
Essentially this line https://github.com/cubewise-code/bedrock/blob/7e147c9245933e4fbeb627417bb5e75047f48f8b/main/%7Dbedrock.cube.view.create.pro#L448 
becomes:
``` 
If ( (pSuppressConsol = 1 % pIncludeDescendants=1) & DTYPE( sDimension, sElement) @= 'C'  );
```
and then you can copy strings on all levels by saying `pSuppressConsol=0, pIncludeDescendants=1`.

Cheers,
Yuri
